{{- $fullName := include "reverse-proxy.fullname" . -}}
{{- $labels := include "reverse-proxy.labels" . -}}
{{- range .Values.instances }}
{{- if .ip -}}
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ $fullName }}-{{ .name }}
  labels:
    {{- $labels | nindent 4 }}
subsets:
  - addresses:
      - ip: {{ .ip }}
    ports:
      - port: {{ .port }}
---
{{- end }}
{{- end }}
