{{- $namePrefix := include "reverse-proxy.fullname" . -}}
{{- $labels := include "reverse-proxy.labels" . -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
{{- $apiVersion := "networking.k8s.io/v1" -}}
{{- else -}}
{{- $apiVersion := "extensions/v1beta1" -}}
{{- end }}
{{- range .Values.instances }}
{{- if .ingress.enabled -}}
{{- $fullName := printf "%s-%s" $namePrefix .name -}}
{{- $svcPort := .port -}}
{{- $secretName := .ingress.secretName -}}
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ $fullName }}
  labels:
    {{- $labels | nindent 4 }}
  {{- with .ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $secretName }}
  tls:
  {{- range .ingress.hosts }}
  - hosts:
    - {{ .host | quote }}
    secretName: {{ $secretName  }}
  {{- end }}
  {{- end }}
  rules:
  {{- range .ingress.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
      {{- if .paths }}
      {{- range .paths }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}
            port:
              number: {{ $svcPort }}
      {{- end }}
      {{- else }}
      - path: /
        backend:
          serviceName: {{ $fullName }}
          servicePort: {{ $svcPort }}
      {{- end }}
  {{- end }}
{{- end }}
---
{{- end }}
