{{- if eq .Values.install_dependencies_only false -}}
{{- if .Values.superuser_password -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "postgresop.labels" $ | nindent 4 }}
    application: spilo
    postgresql-operator: test-postgresql-db
    team: {{ include "postgresop.fullname" . }}
    # xref: https://github.com/helm/helm/issues/3053
    # xref: https://github.com/helm/helm/pull/5290
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  name: {{ include "postgresop.superuser_secret" . }}
stringData:
  username: {{ include "postgresop.superuser" . }}
  password: {{ .Values.superuser_password }}
type: Opaque
{{- end -}}
{{- end -}}
