{{- if eq .Values.install_dependencies_only false -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "postgresop.storageClass" . }}
  labels:
    {{- include "postgresop.labels" . | nindent 4 }}
  annotations:
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
{{- end -}}
