{{- $outer := . -}}
{{- range $index, $certificate := .Values.certificates -}}
{{- with $outer -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $certificate.name }}
  {{- if $certificate.namespace }}
  namespace: {{ $certificate.namespace }}
  {{- end }}
  labels:
    {{- include "certs.labels" . | nindent 4 }}
spec:
  dnsNames:
  {{- toYaml $certificate.dnsNames | nindent 2 }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ $certificate.clusterIssuer }}
  secretName: {{ $certificate.name }}
---
{{- end -}}
{{- end -}}
