{{- $outer := . -}}
{{- range $index, $secret := .Values.secrets -}}
{{- with $outer -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  {{- if $secret.namespace }}
  namespace: {{ $secret.namespace }}
  {{- end }}
  labels:
    {{- include "certs.labels" . | nindent 4 }}
stringData:
  {{- toYaml $secret.stringData | nindent 2 }}
---
{{- end -}}
{{- end -}}
