# Default values for gluster-volume.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

enabled: false

nameOverride: ""
fullnameOverride: ""

accessModes:
- ReadWriteOnce
- ReadOnlyMany

#Size in GiB
size: 1

pvAnnotations: {}

#pvcName: <full name>

global:
  clusterfs:
    heketi_resturl: "http://heketi:8080"
    backup_schedule: "@daily"
    backupPVCPrefix: "backup/db"
    #backupPVCSubpath: "backup/db/myDB"
    #backupPVC: myDBBackup PVC <- required when persistent:true

heketi:
  secretNamespace: "kube-system"
  secretName: "heketi-admin-secret"
  secretRestUser: "user"
  secretRestKey: "key"

glusterfs:
  endpoints: heketi-storage-endpoints
  #path: mitest
  #path: <auto set>
