apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "clusterfs.pvName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clusterfs.labels" . | nindent 4 }}
  annotations:
   {{- .Values.pvAnnotations | toYaml | nindent 4 }}

spec:
  storageClassName: {{ include "clusterfs.storageClass" . }}
  capacity:
    storage: "{{ .Values.size }}Gi"
  accessModes:
    {{- .Values.accessModes| toYaml | nindent 4 }}
  glusterfs:
    {{- include "clusterfs.glusterfs" . | nindent 4 }}
  #Since it is created directly this does not delete it from gluster
  persistentVolumeReclaimPolicy: Delete
