apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "clusterfs.pvcName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clusterfs.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- .Values.accessModes| toYaml | nindent 4 }}
  storageClassName: {{ include "clusterfs.storageClass" . }}
  resources:
    requests:
      storage: "{{ .Values.size }}Gi"
