apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "postgres.scName" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
  annotations:
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: BasePath
        value: {{ include "postgres.basePath" .}}
      - name: StorageType
        value: "hostpath"
provisioner: openebs.io/local
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
