apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chirpstack-packet-multiplexer.fullname" . }}
  labels:
    {{- include "chirpstack-packet-multiplexer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chirpstack-packet-multiplexer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chirpstack-packet-multiplexer.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/ConfigMap.yaml") . | sha256sum }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: semtech
              containerPort: 1700
              protocol: UDP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          
          volumeMounts:
          - name: config
            mountPath: /etc/chirpstack-packet-multiplexer
      volumes:
      - name: config
        configMap:
          name: {{ include "chirpstack-packet-multiplexer.fullname" . }}
          #items:
          #- key: chirpstack-packet-multiplexer.toml
          #  path: chirpstack-packet-multiplexer.toml
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
