apiVersion: v1
kind: Service
metadata:
  name: {{ include "chirpstack-packet-multiplexer.fullname" . }}
  labels:
    {{- include "chirpstack-packet-multiplexer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 1700
      protocol: UDP
      name: semtech
  selector:
    {{- include "chirpstack-packet-multiplexer.selectorLabels" . | nindent 4 }}
