{{- if (.Values.vscode.enabled) and (.Values.vscode.ingress.enabled) }}
{{- $fullName := include "esphome.fullname" . -}}
{{- $servicePort := .Values.vscode.service.port -}}
{{- $ingressPath := .Values.vscode.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-vscode
  labels:
    {{- include "esphome.labels" . | nindent 4 }}
{{- with .Values.vscode.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.vscode.ingress.tls }}
  tls:
  {{- range .Values.vscode.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.vscode.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}
  {{- end }}
{{- end }}
